"""add analysis response fields

Revision ID: 5aaa1632ad5e
Revises: e24f9d5a2f4a
Create Date: 2026-05-16 13:55:42.723510

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5aaa1632ad5e'
down_revision: Union[str, Sequence[str], None] = 'e24f9d5a2f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('fix_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('analyses', sa.Column('debug_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('analyses', sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('analyses', sa.Column('followup_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'followup_questions')
    op.drop_column('analyses', 'assumptions')
    op.drop_column('analyses', 'debug_steps')
    op.drop_column('analyses', 'fix_steps')
    # ### end Alembic commands ###
